const { React, ...rest } = window.__jf()

export default React

// 以下内容是通过 AI 聊天生成的
export const lodash = rest.lodash
export const moment = rest.moment
export const useEffect = rest.useEffect
export const makeAutoObservable = rest.makeAutoObservable
export const runInAction = rest.runInAction
export const observer = rest.observer
export const useLocalObservable = rest.useLocalObservable
export const Button = rest.Button
export const LinkButton = rest.LinkButton
export const InputText = rest.InputText
export const InputTextArea = rest.InputTextArea
export const InputOption = rest.InputOption
export const InputDate = rest.InputDate
export const Checkbox = rest.Checkbox
export const CheckList = rest.CheckList
export const FixedWidthTable = rest.FixedWidthTable
export const FormLayout = rest.FormLayout
export const FontAwesomeIcon = rest.FontAwesomeIcon
export const FaIconBtn = rest.FaIconBtn
export const popup = rest.popup
export const toast = rest.toast
export const GlobalDialog = rest.GlobalDialog
export const getHttpClient = rest.getHttpClient
export const onWebSocketMessage = rest.onWebSocketMessage
export const offWebSocketMessage = rest.offWebSocketMessage
export const stringUtils = rest.stringUtils
export const cn = rest.cn
export const pageStore = rest.pageStore
export const toEntityIndexPage = rest.toEntityIndexPage
export const cqAll = rest.cqAll
export const cqAnd = rest.cqAnd
export const cqOr = rest.cqOr
export const cqGeneral = rest.cqGeneral
export const cqEq = rest.cqEq
export const cqNe = rest.cqNe
export const cqIn = rest.cqIn
export const cqContainIgnoreCase = rest.cqContainIgnoreCase
export const cqIdEq = rest.cqIdEq
export const loadBzConfig = rest.loadBzConfig
export const registerExtPoint = rest.registerExtPoint
export const registerExtPagePoint = rest.registerExtPagePoint
export const toastStore = rest.toastStore
export const popupStore = rest.popupStore
export const findEntityPage = rest.findEntityPage
